// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFAETgrbxfSI1v6l5Ecq9sld6_HnUQJks',
    appId: '1:612579073766:web:d85dae077ecc559444e527',
    messagingSenderId: '612579073766',
    projectId: 'fuego-bites',
    authDomain: 'fuego-bites.firebaseapp.com',
    storageBucket: 'fuego-bites.appspot.com',
    measurementId: 'G-BN2PH1WN71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWGUMBGvRZbisucdilVKvXV3ptv4Vi-Us',
    appId: '1:612579073766:android:144942c816c5ee6144e527',
    messagingSenderId: '612579073766',
    projectId: 'fuego-bites',
    storageBucket: 'fuego-bites.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPYIjTz0zH2ycURQq1T_TsmckMFHN7YeE',
    appId: '1:612579073766:ios:c0f423f1006da69c44e527',
    messagingSenderId: '612579073766',
    projectId: 'fuego-bites',
    storageBucket: 'fuego-bites.appspot.com',
    iosClientId: '612579073766-4ujoqhkld6t10l5v9clfe0l15e38v7gi.apps.googleusercontent.com',
    iosBundleId: 'com.example.fuegoBites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPYIjTz0zH2ycURQq1T_TsmckMFHN7YeE',
    appId: '1:612579073766:ios:2dbb6c45a853d2a244e527',
    messagingSenderId: '612579073766',
    projectId: 'fuego-bites',
    storageBucket: 'fuego-bites.appspot.com',
    iosClientId: '612579073766-o39077og5cmjhs2t9711m7nmv74olgul.apps.googleusercontent.com',
    iosBundleId: 'com.example.fuegoBites.RunnerTests',
  );
}
